# Generated by Django 4.0.3 on 2022-03-13 17:06

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=360)),
            ],
            options={
                'verbose_name_plural': ' 3. Classes',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=360)),
                ('graduation', models.CharField(choices=[('UG', 'UG'), ('PG', 'PG'), ('RESEARCH', 'RESEARCH')], default='UG', max_length=360)),
                ('head', models.CharField(max_length=360)),
            ],
            options={
                'verbose_name_plural': ' 6. Departments',
            },
        ),
        migrations.CreateModel(
            name='Today',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('day_order', models.IntegerField(validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name_plural': " 1. Today's DayOrder",
            },
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('higrade', models.URLField()),
                ('moodle', models.URLField()),
                ('home', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': ' 7. College URLS',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_student', models.BooleanField(default=True)),
                ('is_teacher', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': ' 8. User',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=360)),
                ('name', models.CharField(max_length=360)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.department')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
            options={
                'verbose_name_plural': ' 2. Teachers',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=360)),
                ('sub_id', models.CharField(max_length=360)),
                ('class_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.class')),
            ],
            options={
                'verbose_name_plural': '12. Subjects',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=360)),
                ('name', models.CharField(max_length=360)),
                ('email', models.TextField(blank=True)),
                ('is_leader', models.BooleanField(default=False)),
                ('class_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.class')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
            options={
                'verbose_name_plural': ' 5. Students',
            },
        ),
        migrations.CreateModel(
            name='PersonnelStudentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=360)),
                ('event_name', models.CharField(max_length=360)),
                ('description', models.CharField(blank=True, max_length=1024)),
                ('option', models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('MARKED AS COMPLETE', 'MARKED AS COMPLETE')], default='MARKED AS COMPLETE', max_length=360)),
                ('status', models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('PENDING', 'PENDING'), ('MARKED AS COMPLETE', 'MARKED AS COMPLETE')], default='PENDING', max_length=360)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.student')),
            ],
            options={
                'verbose_name_plural': ' 9. Student Personnel Event',
            },
        ),
        migrations.CreateModel(
            name='DepartmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateField(auto_now=True)),
                ('type', models.CharField(blank=True, max_length=360)),
                ('name', models.CharField(max_length=360)),
                ('due_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=1024)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.department')),
            ],
            options={
                'verbose_name_plural': '10. Department Events',
            },
        ),
        migrations.CreateModel(
            name='DayOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayorder', models.IntegerField()),
                ('hour1', models.CharField(max_length=360)),
                ('hour2', models.CharField(max_length=360)),
                ('hour3', models.CharField(max_length=360)),
                ('hour4', models.CharField(max_length=360)),
                ('hour5', models.CharField(max_length=360)),
                ('hour6', models.CharField(max_length=360)),
                ('class_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.class')),
            ],
            options={
                'verbose_name_plural': ' 4. Time Table',
            },
        ),
        migrations.CreateModel(
            name='CollegeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateField(auto_now=True)),
                ('type', models.CharField(blank=True, max_length=360)),
                ('name', models.CharField(max_length=360)),
                ('due_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=1024)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
            options={
                'verbose_name_plural': '11. College Events',
            },
        ),
        migrations.AddField(
            model_name='class',
            name='class_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.teacher'),
        ),
        migrations.AddField(
            model_name='class',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.department'),
        ),
    ]
