# Generated by Django 4.0.3 on 2022-03-10 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='today',
            name='day_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.dayorder'),
        ),
    ]
