# Generated by Django 4.0.3 on 2022-03-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_today_day_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='today',
            name='day_order',
            field=models.IntegerField(default=1),
        ),
    ]
