# Generated by Django 4.0.3 on 2022-03-10 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_today_day_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=360)),
                ('name', models.CharField(max_length=360)),
                ('description', models.CharField(blank=True, max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelStudentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=360)),
                ('name', models.CharField(max_length=360)),
                ('description', models.CharField(blank=True, max_length=1024)),
                ('option', models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('PENDING', 'PENDING'), ('MARKED AS COMPLETE', 'MARKED AS COMPLETE')], default='MARKED AS COMPLETE', max_length=360)),
                ('status', models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('PENDING', 'PENDING'), ('MARKED AS COMPLETE', 'MARKED AS COMPLETE')], default='PENDING', max_length=360)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=360)),
                ('name', models.CharField(max_length=360)),
                ('description', models.CharField(blank=True, max_length=1024)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.department')),
            ],
        ),
    ]
