# Generated by Django 4.0.3 on 2022-03-10 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_name_personnelstudentevent_event_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': '3. Classes'},
        ),
        migrations.AlterModelOptions(
            name='collegeevent',
            options={'verbose_name_plural': '11. College Events'},
        ),
        migrations.AlterModelOptions(
            name='dayorder',
            options={'verbose_name_plural': '4. Time Table'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': '6. Departments'},
        ),
        migrations.AlterModelOptions(
            name='departmentevent',
            options={'verbose_name_plural': '10. Department Events'},
        ),
        migrations.AlterModelOptions(
            name='personnelstudentevent',
            options={'verbose_name_plural': '9. Student Personnel Event'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '5. Students'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name_plural': '12. Subjects'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': '2. Teachers'},
        ),
        migrations.AlterModelOptions(
            name='today',
            options={'verbose_name_plural': "1. Today's DayOrder"},
        ),
        migrations.AlterModelOptions(
            name='url',
            options={'verbose_name_plural': '7. College URLS'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '8. User'},
        ),
    ]
